version: '3'
services:
  ldap:
    image: osixia/openldap:1.3.0
    environment:
      - "LDAP_ORGANISATION=$LDAP_ORGANISATION"
      - "LDAP_DOMAIN=$LDAP_DOMAIN"
      - "LDAP_ADMIN_PASSWORD=$LDAP_PASSWORD"
      - "LDAP_BASE_DN=$LDAP_BASE_DN"
    networks:
      - ldap
      - ldapinternal
    volumes:
      - "$PWD/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif"
      - "$PWD/acl.ldif:/container/service/slapd/assets/config/bootstrap/ldif/55-acl.ldif"
      - "$DATA_LOCATION/db:/var/lib/ldap"
      - "$DATA_LOCATION?config:/etc/ldap/slapd.d"
    command: --copy-service
  ldap-admin:
    image: osixia/phpldapadmin
    networks:
      - ldapinternal
    environment:
      - "PHPLDAPADMIN_LDAP_HOSTS=ldap"
      - "PHPLDAPADMIN_HTTPS=false"
    ports:
      - ${LOCAL_IP:-127.0.01}:8090:80
networks:
  ldapinternal:
  ldap:
    external:
      name: "ldap"
